Notebook to clean recipe data, results in recipe_clean.csv

In [2]:
import pandas as pd

# Define the file path (use r'' for Windows local paths to avoid errors)
file_path = 'recipes.csv'

# Import the CSV file into a DataFrame
df = pd.read_csv(file_path)

# Display the first 5 rows to verify the import
df.head()

,Unnamed: 0,recipe_name,prep_time,cook_time,total_time,servings,yield,ingredients,directions,rating,url,cuisine_path,nutrition,timing,img_src
0,0,Apple-Cranberry Crostada,NaN,NaN,NaN,8,6 to 8 - servings,"3 tablespoons butter, 2 pounds Granny Smith ap...",Heat butter in a large skillet over medium-hig...,4.4,https://www.allrecipes.com/recipe/76931/apple-...,/Desserts/Fruit Desserts/Apple Dessert Recipes/,"Total Fat 18g 23%, Saturated Fat 7g 34%, Chole...","Servings: 8, Yield: 6 to 8 - servings",https://www.allrecipes.com/thmb/Tf1wH73bfH6Oql...
1,1,Apple Pie by Grandma Ople,30 mins,1 hrs,1 hrs 30 mins,8,1 9-inch pie,"8 small Granny Smith apples, or as needed, ½ c...","Peel and core apples, then thinly slice. Set a...",4.8,https://www.allrecipes.com/recipe/12682/apple-...,/Desserts/Pies/Apple Pie Recipes/,"Total Fat 19g 24%, Saturated Fat 9g 46%, Chole...","Prep Time: 30 mins, Cook Time: 1 hrs, Total Ti...",https://www.allrecipes.com/thmb/1I95oiTGz6aEpu...
2,2,Sarah's Homemade Applesauce,10 mins,15 mins,25 mins,4,NaN,"4 apples - peeled, cored and chopped, ¾ cup w...","Combine apples, water, sugar, and cinnamon in ...",4.8,https://www.allrecipes.com/recipe/51301/sarahs...,/Side Dish/Applesauce Recipes/,"Total Fat 0g 0%, Sodium 3mg 0%, Total Carbohyd...","Prep Time: 10 mins, Cook Time: 15 mins, Total ...",https://www.allrecipes.com/thmb/VY5d0tZHB8xz6y...
3,3,Apple Crisp,30 mins,45 mins,1 hrs 15 mins,12,1 9x13-inch pan,"10 cups all-purpose apples, peeled, cored and ...",Preheat the oven to 350 degrees F (175 degrees...,4.7,https://www.allrecipes.com/recipe/12409/apple-...,/Desserts/Crisps and Crumbles Recipes/Apple Cr...,"Total Fat 8g 11%, Saturated Fat 5g 25%, Choles...","Prep Time: 30 mins, Cook Time: 45 mins, Total ...",https://www.allrecipes.com/thmb/uAzhPOh86PfR-N...
4,4,Apple Pie Filling,20 mins,20 mins,2 hrs 40 mins,40,5 9-inch pies,"18 cups thinly sliced apples, 3 tablespoons le...",Toss apples with lemon juice in a large bowl a...,4.7,https://www.allrecipes.com/recipe/12681/apple-...,/Desserts/Pies/Apple Pie Recipes/,"Total Fat 0g 0%, Sodium 61mg 3%, Total Carbohy...","Prep Time: 20 mins, Cook Time: 20 mins, Additi...",https://www.allrecipes.com/thmb/c0bbYaS1V_mTt_...

In [4]:
pd.set_option('display.max_colwidth', None)
df['url']

0                https://www.allrecipes.com/recipe/76931/apple-cranberry-crostada/
1               https://www.allrecipes.com/recipe/12682/apple-pie-by-grandma-ople/
2                       https://www.allrecipes.com/recipe/51301/sarahs-applesauce/
3                          https://www.allrecipes.com/recipe/12409/apple-crisp-ii/
4                       https://www.allrecipes.com/recipe/12681/apple-pie-filling/
                                           ...
1085                      https://www.allrecipes.com/recipe/240653/date-nut-balls/
1086                          https://www.allrecipes.com/recipe/7509/jamaica-cake/
1087                      https://www.allrecipes.com/recipe/242153/best-hot-sauce/
1088                 https://www.allrecipes.com/recipe/51446/moist-date-nut-bread/
1089    https://www.allrecipes.com/recipe/254452/chef-johns-chocolate-energy-bars/
Name: url, Length: 1090, dtype: object

In [7]:
pd.reset_option('all')
df['directions']

C:\Users\matth\AppData\Local\Temp\ipykernel_22084\3555157726.py:1: FutureWarning: data_manager option is deprecated and will be removed in a future version. Only the BlockManager will be available.
  pd.reset_option('all')
C:\Users\matth\AppData\Local\Temp\ipykernel_22084\3555157726.py:1: FutureWarning: use_inf_as_na option is deprecated and will be removed in a future version. Convert inf values to NaN before operating instead.
  pd.reset_option('all')

0       Heat butter in a large skillet over medium-hig...
1       Peel and core apples, then thinly slice. Set a...
2       Combine apples, water, sugar, and cinnamon in ...
3       Preheat the oven to 350 degrees F (175 degrees...
4       Toss apples with lemon juice in a large bowl a...
                              ...
1085    Melt butter in a saucepan over medium heat; co...
1086    Mix together sugar, vegetable oil, pecans, flo...
1087    Place peppers, onion, dates, basil, parsley, t...
1088    Preheat the oven to 350 degrees F (175 degrees...
1089    Place cashews, almonds, coconut, dates, cocoa,...
Name: directions, Length: 1090, dtype: object

In [8]:
# Get base data for recipe table
recipe_df = df[['recipe_name', 'prep_time', 'cook_time', 'total_time', 'servings', 'yield', 'rating', 'url', 'img_src']]
recipe_df

,recipe_name,prep_time,cook_time,total_time,servings,yield,rating,url,img_src
0,Apple-Cranberry Crostada,NaN,NaN,NaN,8,6 to 8 - servings,4.4,https://www.allrecipes.com/recipe/76931/apple-...,https://www.allrecipes.com/thmb/Tf1wH73bfH6Oql...
1,Apple Pie by Grandma Ople,30 mins,1 hrs,1 hrs 30 mins,8,1 9-inch pie,4.8,https://www.allrecipes.com/recipe/12682/apple-...,https://www.allrecipes.com/thmb/1I95oiTGz6aEpu...
2,Sarah's Homemade Applesauce,10 mins,15 mins,25 mins,4,NaN,4.8,https://www.allrecipes.com/recipe/51301/sarahs...,https://www.allrecipes.com/thmb/VY5d0tZHB8xz6y...
3,Apple Crisp,30 mins,45 mins,1 hrs 15 mins,12,1 9x13-inch pan,4.7,https://www.allrecipes.com/recipe/12409/apple-...,https://www.allrecipes.com/thmb/uAzhPOh86PfR-N...
4,Apple Pie Filling,20 mins,20 mins,2 hrs 40 mins,40,5 9-inch pies,4.7,https://www.allrecipes.com/recipe/12681/apple-...,https://www.allrecipes.com/thmb/c0bbYaS1V_mTt_...
...,...,...,...,...,...,...,...,...,...
1085,Date-Nut Balls,15 mins,10 mins,30 mins,48,4 dozen balls,3.8,https://www.allrecipes.com/recipe/240653/date-...,https://www.allrecipes.com/thmb/LXm_15zLymhZ7c...
1086,Jamaica Cake,NaN,NaN,NaN,14,1 - 13x9 inch pan,4.6,https://www.allrecipes.com/recipe/7509/jamaica...,https://www.allrecipes.com/thmb/tI7g5xY5-qPV5v...
1087,Best Hot Sauce,10 mins,20 mins,30 mins,100,2 cups,4.9,https://www.allrecipes.com/recipe/242153/best-...,https://www.allrecipes.com/thmb/80wUYzFvbycfxx...
1088,Moist Date Nut Bread,15 mins,50 mins,1 hrs 35 mins,12,1 9x5-inch loaf,4.5,https://www.allrecipes.com/recipe/51446/moist-...,https://www.allrecipes.com/thmb/bYsnompJZ6UAF9...
1089,Chef John's Chocolate Energy Bars,15 mins,NaN,3 hrs,12,12 bars,4.8,https://www.allrecipes.com/recipe/254452/chef-...,https://www.allrecipes.com/thmb/IOoj42MMo8YNKW...

In [ ]:
pd.set_option('display.max_colwidth', None)
df['nutrition']

# Want to extract nutrition data into new columns
# ['total_fat', 'sat_fat', 'cholesterol', 
#  'sodium', 'total_carbohydrate', 'dietary_fiber', 
#  'total_sugars', 'protein', 'vitamin_c', 'calcium', 
#  'iron', 'potassium']

0         Total Fat 18g 23%, Saturated Fat 7g 34%, Cholesterol 19mg 6%, Sodium 128mg 6%, Total Carbohydrate 60g 22%, Dietary Fiber 5g 16%, Total Sugars 40g, Protein 4g, Vitamin C 8mg 42%, Calcium 35mg 3%, Iron 1mg 6%, Potassium 245mg 5%
1                          Total Fat 19g 24%, Saturated Fat 9g 46%, Cholesterol 31mg 10%, Sodium 124mg 5%, Total Carbohydrate 52g 19%, Dietary Fiber 3g 10%, Protein 2g, Vitamin C 5mg 27%, Calcium 23mg 2%, Iron 1mg 6%, Potassium 156mg 3%
2                                                        Total Fat 0g 0%, Sodium 3mg 0%, Total Carbohydrate 32g 12%, Dietary Fiber 4g 13%, Total Sugars 27g, Protein 0g, Vitamin C 6mg 32%, Calcium 13mg 1%, Iron 0mg 1%, Potassium 150mg 3%
3           Total Fat 8g 11%, Saturated Fat 5g 25%, Cholesterol 20mg 7%, Sodium 98mg 4%, Total Carbohydrate 61g 22%, Dietary Fiber 3g 12%, Total Sugars 44g, Protein 2g, Vitamin C 4mg 21%, Calcium 36mg 3%, Iron 1mg 6%, Potassium 162mg 3%
4                                                          Total Fat 0g 0%, Sodium 61mg 3%, Total Carbohydrate 33g 12%, Dietary Fiber 1g 5%, Total Sugars 28g, Protein 0g, Vitamin C 3mg 16%, Calcium 7mg 1%, Iron 0mg 1%, Potassium 63mg 1%
                                                                                                                        ...
1085                 Total Fat 5g 6%, Saturated Fat 2g 12%, Cholesterol 9mg 3%, Sodium 33mg 1%, Total Carbohydrate 8g 3%, Dietary Fiber 1g 2%, Total Sugars 7g, Protein 0g, Vitamin C 1mg 4%, Calcium 4mg 0%, Iron 1mg 3%, Potassium 32mg 1%
1086    Total Fat 33g 43%, Saturated Fat 4g 21%, Cholesterol 40mg 13%, Sodium 272mg 12%, Total Carbohydrate 61g 22%, Dietary Fiber 3g 9%, Total Sugars 37g, Protein 6g, Vitamin C 5mg 27%, Calcium 25mg 2%, Iron 2mg 11%, Potassium 201mg 4%
1087                                    Total Fat 1g 1%, Saturated Fat 0g 1%, Sodium 29mg 1%, Total Carbohydrate 1g 0%, Dietary Fiber 0g 0%, Total Sugars 0g, Protein 0g, Vitamin C 11mg 57%, Calcium 2mg 0%, Iron 0mg 1%, Potassium 21mg 0%
1088      Total Fat 10g 13%, Saturated Fat 3g 16%, Cholesterol 26mg 9%, Sodium 365mg 16%, Total Carbohydrate 47g 17%, Dietary Fiber 4g 14%, Total Sugars 30g, Protein 4g, Vitamin C 0mg 2%, Calcium 51mg 4%, Iron 2mg 8%, Potassium 312mg 7%
1089                         Total Fat 22g 28%, Saturated Fat 7g 36%, Sodium 230mg 10%, Total Carbohydrate 36g 13%, Dietary Fiber 7g 25%, Total Sugars 21g, Protein 8g, Vitamin C 0mg 1%, Calcium 59mg 5%, Iron 3mg 17%, Potassium 515mg 11%
Name: nutrition, Length: 1090, dtype: object

In [15]:
# Define the mapping of column names and their specific regex patterns
patterns = {
    'total_fat (g)': r'Total Fat (\d+g)',
    'sat_fat (g)': r'Saturated Fat (\d+g)',
    'cholesterol (mg)': r'Cholesterol (\d+mg)',
    'sodium (mg)': r'Sodium (\d+mg)',
    'total_carbohydrate (g)': r'Total Carbohydrate (\d+g)',
    'dietary_fiber (g)': r'Dietary Fiber (\d+g)',
    'total_sugars (g)': r'Total Sugars (\d+g)',
    'protein (g)': r'Protein (\d+g)',
    'vitamin_c (mg)': r'Vitamin C (\d+mg)',
    'calcium (mg)': r'Calcium (\d+mg)',
    'iron (mg)': r'Iron (\d+mg)',
    'potassium (mg)': r'Potassium (\d+mg)'
}

# Create the new nutrition_df by extracting each pattern from the original column
nutrition_df = pd.DataFrame()

for col, regex in patterns.items():
    nutrition_df[col] = df['nutrition'].str.extract(regex)

# Display the new DataFrame
nutrition_df.head()

,total_fat (g),sat_fat (g),cholesterol (mg),sodium (mg),total_carbohydrate (g),dietary_fiber (g),total_sugars (g),protein (g),vitamin_c (mg),calcium (mg),iron (mg),potassium (mg)
0,18g,7g,19mg,128mg,60g,5g,40g,4g,8mg,35mg,1mg,245mg
1,19g,9g,31mg,124mg,52g,3g,NaN,2g,5mg,23mg,1mg,156mg
2,0g,NaN,NaN,3mg,32g,4g,27g,0g,6mg,13mg,0mg,150mg
3,8g,5g,20mg,98mg,61g,3g,44g,2g,4mg,36mg,1mg,162mg
4,0g,NaN,NaN,61mg,33g,1g,28g,0g,3mg,7mg,0mg,63mg

In [16]:
# Strip 'g' and 'mg' from all values in the new DataFrame
# We use regex=True to replace both units at once
nutrition_df = nutrition_df.replace(r'g|mg', '', regex=True)

# Convert the entire DataFrame to numeric (floats) for analysis
nutrition_df = nutrition_df.apply(pd.to_numeric, errors='coerce')

nutrition_df.head()

,total_fat (g),sat_fat (g),cholesterol (mg),sodium (mg),total_carbohydrate (g),dietary_fiber (g),total_sugars (g),protein (g),vitamin_c (mg),calcium (mg),iron (mg),potassium (mg)
0,18.0,7.0,19.0,128.0,60,5.0,40.0,4.0,8.0,35.0,1.0,245
1,19.0,9.0,31.0,124.0,52,3.0,NaN,2.0,5.0,23.0,1.0,156
2,0.0,NaN,NaN,3.0,32,4.0,27.0,0.0,6.0,13.0,0.0,150
3,8.0,5.0,20.0,98.0,61,3.0,44.0,2.0,4.0,36.0,1.0,162
4,0.0,NaN,NaN,61.0,33,1.0,28.0,0.0,3.0,7.0,0.0,63

In [17]:
# Append the cleaned nutrition_df columns back to the original df
recipe_df = pd.concat([recipe_df, nutrition_df], axis=1)

# Verify the result
recipe_df.head()

,recipe_name,prep_time,cook_time,total_time,servings,yield,rating,url,img_src,total_fat (g),...,cholesterol (mg),sodium (mg),total_carbohydrate (g),dietary_fiber (g),total_sugars (g),protein (g),vitamin_c (mg),calcium (mg),iron (mg),potassium (mg)
0,Apple-Cranberry Crostada,NaN,NaN,NaN,8,6 to 8 - servings,4.4,https://www.allrecipes.com/recipe/76931/apple-cranberry-crostada/,https://www.allrecipes.com/thmb/Tf1wH73bfH6OqlfQySSDtMaP-nw=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/517708-5f57072dedb04a389edab3e141517d4d.jpg,18.0,...,19.0,128.0,60,5.0,40.0,4.0,8.0,35.0,1.0,245
1,Apple Pie by Grandma Ople,30 mins,1 hrs,1 hrs 30 mins,8,1 9-inch pie,4.8,https://www.allrecipes.com/recipe/12682/apple-pie-by-grandma-ople/,https://www.allrecipes.com/thmb/1I95oiTGz6aEpuHd2DAr33w7Mgg=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/12682-apple-pie-by-grandma-ople-natasha-titanov-1x1-1-7f1cd9f631d24ff0b90cac0163247686.jpg,19.0,...,31.0,124.0,52,3.0,NaN,2.0,5.0,23.0,1.0,156
2,Sarah's Homemade Applesauce,10 mins,15 mins,25 mins,4,NaN,4.8,https://www.allrecipes.com/recipe/51301/sarahs-applesauce/,https://www.allrecipes.com/thmb/VY5d0tZHB8xz6y-ef586jR050FE=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/25840-Sarahs-Applesauce-2000-56080bc8aac64df59aeec895f1875fc0.jpg,0.0,...,NaN,3.0,32,4.0,27.0,0.0,6.0,13.0,0.0,150
3,Apple Crisp,30 mins,45 mins,1 hrs 15 mins,12,1 9x13-inch pan,4.7,https://www.allrecipes.com/recipe/12409/apple-crisp-ii/,https://www.allrecipes.com/thmb/uAzhPOh86PfR-NIT1_dQ5c9bhag=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/12409-apple-crisp-MFS-027-c2f142105db44206856af57c388db3ee.jpg,8.0,...,20.0,98.0,61,3.0,44.0,2.0,4.0,36.0,1.0,162
4,Apple Pie Filling,20 mins,20 mins,2 hrs 40 mins,40,5 9-inch pies,4.7,https://www.allrecipes.com/recipe/12681/apple-pie-filling/,https://www.allrecipes.com/thmb/c0bbYaS1V_mTt_fb85yo0gPcYUM=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/12681-apple-pie-filling-beauty-1x1-BP-2876-ed43a184f9564f4a8dc893c4ae8d561f.jpg,0.0,...,NaN,61.0,33,1.0,28.0,0.0,3.0,7.0,0.0,63

In [19]:
recipe_df.to_csv('recipe_clean.csv', index=False)